version: 2
project_name: tmplhate

# Cross-platform Go builds
builds:
  - goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/ericpfisher/tmplhate/cmd.Version={{.Version}}
      - -X github.com/ericpfisher/tmplhate/cmd.Commit={{.ShortCommit}}
      - -X github.com/ericpfisher/tmplhate/cmd.Date={{.Date}}
    env:
      - CGO_ENABLED=0

archives:
  - formats:
      - tar.gz
    files:
      - LICENSE

# Docker multi-arch build (default)
dockers_v2:
  - images:
      - ericpfisher/tmplhate
      - ghcr.io/ericpfisher/tmplhate
    tags:
      - v{{ .Version }}
      - latest
    dockerfile: Dockerfile

sboms:
  - id: default

# Release to GitHub
release:
  github:
    owner: ericpfisher
    name: tmplhate
  draft: false
  prerelease: false
